{{/* Setting defaults if they are omitted. */}}
{{- $isOpenshiftCluster := .Capabilities.APIVersions.Has "apps.openshift.io/v1" -}}
apiVersion: batch/v1
kind: Job
metadata:
  name: pxcentral-ls-cleanup
  namespace: {{ .Release.Namespace }}
  annotations:
    helm.sh/hook: pre-delete
    helm.sh/hook-weight: "10"
    helm.sh/hook-delete-policy: before-hook-creation
  labels:
    app.kubernetes.io/component: pxcentral-ls-cleanup
{{- include "px-license-server.labels" . | nindent 4 }}
spec:
  template:
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: px/ls
                operator: NotIn
                values:
                - "false"
      serviceAccountName: pxcentral-license-server
      {{- if $isOpenshiftCluster}}
      {{- else }}
      securityContext:
{{ toYaml .Values.securityContext | indent 8 }}
      {{- end }}
      containers:
      - name: pxcentral-ls-cleanup
        image: {{ printf "%s/%s/%s:%s" .Values.images.pxLicenseHAConfigContainerImage.registry .Values.images.pxLicenseHAConfigContainerImage.repo .Values.images.pxLicenseHAConfigContainerImage.imageName .Values.images.pxLicenseHAConfigContainerImage.tag }}
        imagePullPolicy: {{ .Values.images.pullPolicy }}
        env:
          - name: LOG_LEVEL
            value: INFO
          - name: PXC_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
        command: ["python",  "/pxcentral-license-server/pxc-ls-cleanup.py"]
      {{- if .Values.images.pullSecrets }}
      imagePullSecrets:
        {{- range $sec := .Values.images.pullSecrets }}
        - name: {{ $sec | quote }}
        {{- end }}
      {{- end }}
      restartPolicy: Never
  backoffLimit: 5
  activeDeadlineSeconds: 2400