apiVersion: v2
name: px-observability-ui
description: >-
  An in-cluster observability, manageability and supportability UI for your Portworx Cluster.
type: application
version: 1.0.0-ea.rc.3
appVersion: "1.0.0-ea"
home: https://www.everpuredata.com/products/kubernetes-data-management.html
sources:
  - https://github.com/portworx/helm
icon: https://raw.githubusercontent.com/portworx/helm/master/doc/media/k8s-porx.png