{{/* PX-Backup Telemetry Logs Collector ConfigMaps */}}
{{- $pxBackupEnabled := .Values.pxbackup.enabled | default false }}
{{- $telemetryEnabled := .Values.telemetry.enabled | default false }}
{{- $logsEnabled := .Values.telemetry.logsCollector.enabled | default false }}
{{- if and (eq $pxBackupEnabled true) (eq $telemetryEnabled true) (eq $logsEnabled true) }}
---
# Log Upload Service Configuration
apiVersion: v1
kind: ConfigMap
metadata:
  name: px-backup-telemetry-logs-upload-config
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: px-backup-telemetry
    app.kubernetes.io/name: logs-collector
{{- include "px-central.labels" . | nindent 4 }}
data:
  ccm.properties: |
    {
      "product_name": "portworx",
      "port": "9090",
      "envoy_port": "12002",
      "logupload": {
        "logfile_patterns": [
          "/var/cores/px-backup-logs-*.log.gz",
          "/var/cores/px-backup-reporting-*.log.gz",
          "/var/cores/px-backup-metrics-*.log.gz",
          "/var/cores/px-backup-db-*.tar.gz"
        ],
        "logfile_retention_count": 5,
        "phonehome_hour_range": 744,
        "always_scan_range_days": 7,
        "max_retry_per_hour": 5
      }
    }
{{- end }}
