apiVersion: v1
kind: Secret
metadata:
  name: pxc-backup-secret
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: px-backup
{{- include "px-central.labels" . | nindent 4 }}
type: Opaque
stringData:
  OIDC_CLIENT_ID: {{ .Values.oidc.centralOIDC.clientId | quote}}
  OIDC_ENDPOINT: "http://pxcentral-keycloak-http/auth/realms/master"
