{{- if .Values.ui.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "px-observability-ui.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "px-observability-ui.labels" . | nindent 4 }}
{{- end }}
