apiVersion: v1
kind: ConfigMap
metadata:
  name: pxcentral-monitor-configmap
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: pxcentral-monitor
{{- include "px-monitor.labels" . | nindent 4 }}
data:
  INTERNAL_PX_MONITOR: "{{ .Values.pxmonitor.enabled }}"
  METRICS_STORE_ENDPOINT: "{{ .Values.pxmonitor.pxCentralEndpoint }}"
  GRAFANA_ENDPOINT: "{{ .Values.pxmonitor.pxCentralEndpoint }}"
  SSL_ENABLED: "{{ .Values.pxmonitor.sslEnabled }}"