{{/* Setting defaults if they are omitted. */}}
{{- $lsEnabled := .Values.pxlicenseserver.enabled | default false -}}
{{- if eq $lsEnabled true }}
apiVersion: v1
kind: Secret
metadata:
  labels:
    app.kubernetes.io/component: px-license-server
{{- include "px-central.labels" . | nindent 4 }}
  name: px-license-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  PX_LICENSE_USER: {{ .Values.pxlicenseserver.adminUserName | quote}}
  PX_LICENSE_PASSWORD: {{ .Values.pxlicenseserver.adminUserPassword | quote}}
{{- end -}}