persistentStorage:
  enabled: true
  storageClassName:
  cassandra:
    storage: 50Gi
  grafana:
    storage: 20Gi
  consul:
    storage: 8Gi
  alertManager:
    storage: 2Gi
  ingester:
    storage: 2Gi
  mysqlVolumeSize: "100Gi"
  etcdVolumeSize: "64Gi"
  keycloakThemeVolumeSize: "5Gi"
  keycloakBackendVolumeSize: "10Gi"

storkRequired: false

pxcentralDBPassword: Password1
caCertsSecretName: ""

oidc:
  centralOIDC:
    enabled: true
    defaultUsername: admin
    defaultPassword: admin
    defaultEmail: admin@portworx.com
    keyCloakBackendUserName: keycloak
    keyCloakBackendPassword: keycloak
    clientId: "pxcentral"
    updateAdminProfile: true

  externalOIDC:
    enabled: false
    clientID:
    clientSecret:
    endpoint:

pxbackup:
  enabled: false
  orgName: default
  callHome: true
  nodeAffinityLabel:

pxlicenseserver:
  enabled: false
  internal:
    enabled: true
    lsTypeUAT: false
    lsTypeAirgapped: false
  external:
    enabled: false
  mainNodeIP: ""
  backupNodeIP: ""
  adminUserName: admin
  adminUserPassword: Password@1

pxmonitor:
  enabled: false
  pxCentralEndpoint: 
  sslEnabled: false
  oidcClientID: pxcentral
  oidcClientSecret: ""
  nodeAffinityLabel:

service:
  pxBackupUIServiceType: "LoadBalancer"
  grafanaServiceType: "NodePort"
  cortexNginxServiceType: "NodePort"

## Memory settings: These are calculated automatically unless specified otherwise
## To run on environments with little resources (<= 8GB), tune your heap settings:
## maxHeapSize:
## - calculate 1/2 ram and cap to 1024MB
## - calculate 1/4 ram and cap to 8192MB
## - pick the max
## newHeapSize:
## A good guideline is 100 MB per CPU core.
## - min(100 * num_cores, 1/4 * heap size)
##
# maxHeapSize: 4G
# newHeapSize: 800M

cassandra:
  jvm:
    maxHeapSize:
    newHeapSize:

installCRDs: false
clusterDomain: "cluster.local"
cassandraUsername: cassandra
cassandraPassword: cassandra

operatorToChartUpgrade: false

securityContext:
  runAsUser: 1000
  fsGroup: 1000
  runAsNonRoot: true

images:
  pullSecrets:
    - docregistry-secret
  pullPolicy: Always

  pxcentralApiServerImage:
    registry: docker.io
    repo: portworx
    imageName: pxcentral-onprem-api
    tag: 1.2.1
  pxcentralFrontendImage:
    registry: docker.io
    repo: portworx
    imageName: pxcentral-onprem-ui-frontend
    tag: 1.2.2
  pxcentralBackendImage:
    registry: docker.io
    repo: portworx
    imageName: pxcentral-onprem-ui-backend
    tag: 1.2.2
  pxcentralMiddlewareImage:
    registry: docker.io
    repo: portworx
    imageName: pxcentral-onprem-ui-lhbackend
    tag: 1.2.2
  pxBackupImage:
    registry: docker.io
    repo: portworx
    imageName: px-backup
    tag: 1.2.2
  postInstallSetupImage:
    registry: docker.io
    repo: portworx
    imageName: pxcentral-onprem-post-setup
    tag: 1.2.2
  etcdImage:
    registry: docker.io
    repo: bitnami
    imageName: etcd
    tag: 3.4.13-debian-10-r22
  keycloakBackendImage:
    registry: docker.io
    repo: bitnami
    imageName: postgresql
    tag: 11.7.0-debian-10-r9
  keycloakFrontendImage:
    registry: docker.io
    repo: jboss
    imageName: keycloak
    tag: 9.0.2
  keycloakLoginThemeImage:
    registry: docker.io
    repo: portworx
    imageName: keycloak-login-theme
    tag: 1.0.4
  keycloakInitContainerImage:
    registry: docker.io
    repo: library
    imageName: busybox
    tag: 1.31
  mysqlImage:
    registry: docker.io
    repo: library
    imageName: mysql
    tag: 5.7.22

  licenseServerImage:
    registry: docker.io
    repo: portworx
    imageName: px-els
    tag: 1.0.0
  pxLicenseHAConfigContainerImage:
    registry: docker.io
    repo: portworx
    imageName: pxcentral-onprem-els-ha-setup
    tag: 1.1.1

  cortexImage:
    registry: quay.io
    repo: cortexproject
    imageName: cortex
    tag: v1.1.0
  cassandraImage:
    registry: docker.io
    repo: bitnami
    imageName: cassandra
    tag: 3.11.6-debian-10-r153
  proxyConfigImage:
    registry: docker.io
    repo: library
    imageName: nginx
    tag: 1.17
  consulImage:
    registry: docker.io
    repo: bitnami
    imageName: consul
    tag: 1.8.0-debian-10-r24
  dnsmasqImage:
    registry: docker.io
    repo: pwxbuild
    imageName: go-dnsmasq
    tag: release-1.0.7
  grafanaImage:
    registry: docker.io
    repo: grafana
    imageName: grafana
    tag: 7.1.3
  prometheusImage:
    registry: quay.io
    repo: prometheus
    imageName: prometheus
    tag: v2.7.1
  prometheusConfigReloadImage:
    registry: quay.io
    repo: coreos
    imageName: configmap-reload
    tag: v0.0.1
  prometheusConfigReloadrImage:
    registry: quay.io
    repo: coreos
    imageName: prometheus-config-reloader
    tag: v0.34.0
  prometheusOperatorImage:
    registry: quay.io
    repo: coreos
    imageName: prometheus-operator
    tag: v0.34.0
  pxMonitorPostInstallSetup:
    registry: docker.io
    repo: portworx
    imageName: pxcentral-monitor-post-install-setup
    tag: 1.2.1
  memcachedMetricsImage:
    registry: quay.io
    repo: prometheus
    imageName: memcached-exporter
    tag: v0.4.1
  memcachedIndexImage:
    registry: docker.io
    repo: library
    imageName: memcached
    tag: 1.5.7-alpine
  memcachedImage:
    registry: docker.io
    repo: library
    imageName: memcached
    tag: 1.5.12-alpine