apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: pg-01
  labels:
    app.kubernetes.io/name: postgres
    app.kubernetes.io/instance: pg-01
type: Opaque
stringData:
  POSTGRES_DB: "appdb"
  POSTGRES_USER: "appuser"
  POSTGRES_PASSWORD: "Password1"
