#Only if Zerostorage is true. 
{{- if (.Values.zeroStorage) and (eq .Values.zeroStorage true) -}}

#Setting defaults if they are omitted.
{{- $dataInterface := .Values.dataInterface | default "none" }}
{{- $managementInterface := .Values.managementInterface | default "none" }}

{{- $lighthouseToken := .Values.lighthouse.token | default "none" }}
{{- $envVars := .Values.envVars | default "none" }}

{{- $etcdCredentials := .Values.etcd.credentials | default "none:none" }}
{{- $etcdCA := .Values.etcd.ca | default "none" }}
{{- $etcdCert := .Values.etcd.cert | default "none" }}
{{- $etcdKey := .Values.etcd.key | default "none" }}
{{- $etcdACL := .Values.etcd.acl | default "none" }}

apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: portworx-zerostorage
  namespace: kube-system
spec:
  minReadySeconds: 0
  
  {{- if eq (.Values.deploymentType | upper | lower) "oci" }}
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  
  {{- else if eq (.Values.deploymentType | upper | lower) "docker" }}
  updateStrategy:
    type: OnDelete
  
  {{- end }}
  template:
    metadata:
      labels:
        app:  portworx-zerostorage
        name: portworx
        # {{- include "px.labels" . | indent 8 }}  
      namespace: kube-system
    spec:
      tolerations:
      - key: node-role.kubernetes.io/master
        operator: Equal
        effect: NoSchedule
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node-role.kubernetes.io/master
                operator: Exists
              - key: px/enabled
                operator: NotIn
                values:
                - "false"
      hostNetwork: true
      hostPID: true
      containers:
        - name: portworx

          {{- if eq (.Values.deploymentType | upper | lower) "oci" }}
          image: portworx/oci-monitor:{{ required  "A valid Image tag. Should be in the SemVer format" .Values.imageVersion }}

          {{- else if eq (.Values.deploymentType | upper | lower) "docker" }}
          image: portworx/px-enterprise:{{ required "A valid Image tag. Should be in the SemVer format" .Values.imageVersion }}

          {{- end }}          
          terminationMessagePath: "/tmp/px-termination-log"
          imagePullPolicy: Always
          args:
  
          {{- with .Values }}
            [
              "-k", 
              "{{ required "A valid ETCD url in the format etcd:http://<your-etcd-endpoint>:2379 is required" .etcdEndPoint }}", 
              "-c", 
              "{{ required "Clustername cannot be empty" .clusterName }}", 

              {{- if not (eq $dataInterface "none") }}
              "-d",
              "{{ $dataInterface }}",
              {{- end }}

              {{- if not (eq $managementInterface "none") }}
              "-m",
              "{{ $managementInterface }}",
              {{- end }}


              {{- if not (eq $lighthouseToken "none") }}
              "-t",
              "{{ $lighthouseToken }}",
              {{- end }}

              {{- if not (eq $etcdCredentials "none:none") }}
              "-userpwd",
              "{{ $etcdCredentials }}",
              {{- end }}

              {{- if not (eq $etcdCA "none") }}
              "-ca",
              "{{ $etcdCA }}",
              {{- end }}

              {{- if not (eq $etcdCert "none") }}
              "-cert",
              "{{ $etcdCert }}",
              {{- end }}

              {{- if not (eq $etcdKey "none") }}
              "-key",
              "{{ $etcdKey }}",
              {{- end }}              

              {{- if not (eq $etcdACL "none") }}
              "-acltoken",
              "{{ $etcdACL }}",
              {{- end }}              

              "-x",
              "kubernetes",
              "-z"
             ]
  
          {{- end }}   
          env:
            - name: "PX_TEMPLATE_VERSION"
              value: "v2"
              {{- if not (eq $envVars "none") }}
              {{- $vars := $envVars | split ":" }}
              {{- range $key, $val := $vars }}
              {{-  $envVariable := $val | split "=" -}}
            - name: {{ $envVariable._0 | quote }}
              value: {{ $envVariable._1 | quote }}
              {{- end -}}
              {{- end }}
              
          livenessProbe:
            periodSeconds: 30
            initialDelaySeconds: 840 # allow image pull in slow networks
            httpGet:
              host: 127.0.0.1
              path: /status
              port: 9001
          readinessProbe:
            periodSeconds: 10
            httpGet:
              host: 127.0.0.1
  
              {{- if eq (.Values.deploymentType | upper | lower) "oci" }}
              path: /health
              port: 9015
  
              {{- else if eq (.Values.deploymentType | upper | lower) "docker" }}
              path: /v1/cluster/nodehealth
              port: 9001
  
              {{- end }}
          securityContext:
            privileged: true
          volumeMounts:
            - name: dockersock
              mountPath: /var/run/docker.sock
          {{- if (.Values.openshiftInstall) and (eq .Values.openshiftInstall true)}}
            - name: kubelet
              mountPath: /var/lib/origin/openshift.local.volumes:shared
          {{- else }}
            - name: kubelet
              mountPath: /var/lib/kubelet:shared
          {{- end }}
            - name: libosd
              mountPath: /var/lib/osd:shared
            - name: etcpwx
              mountPath: /etc/pwx

          {{- if eq (.Values.deploymentType | upper | lower) "oci" }}
            - name: optpwx
              mountPath: /opt/pwx
            - name: proc1nsmount
              mountPath: /host_proc/1/ns
            - name: sysdmount
              mountPath: /etc/systemd/system

          {{- else if eq (.Values.deploymentType | upper | lower) "docker" }}
            - name: optpwx
              mountPath: /export_bin
            - name: dev
              mountPath: /dev
            - name: cores
              mountPath: /var/cores
            - name: src
              mountPath: /usr/src
            - name: dockerplugins
              mountPath: /run/docker/plugins
            - name: hostproc
              mountPath: /hostproc
          {{- end }}
      restartPolicy: Always
      serviceAccountName: px-account
      volumes:
        - name: dockersock
          hostPath:
            path: /var/run/docker.sock
          {{- if (.Values.openshiftInstall) and (eq .Values.openshiftInstall true)}}
        - name: kubelet
          hostPath:
            path: /var/lib/origin/openshift.local.volumes:shared
          {{- else }}
        - name: kubelet
          hostPath:
            path: /var/lib/kubelet
          {{- end }}
        - name: libosd
          hostPath:
            path: /var/lib/osd
        - name: etcpwx
          hostPath:
            path: /etc/pwx
        
        {{- if eq (.Values.deploymentType | upper | lower) "oci" }}
        - name: optpwx
          hostPath:
            path: /opt/pwx
        - name: proc1nsmount
          hostPath:
            path: /proc/1/ns
        - name: sysdmount
          hostPath:
            path: /etc/systemd/system

        {{- else if eq (.Values.deploymentType | upper | lower) "docker" }}
        - name: optpwx
          hostPath:
            path: /opt/pwx/bin
        - name: dev
          hostPath:
            path: /dev
        - name: cores
          hostPath:
            path: /var/cores
        - name: src
          hostPath:
            path: /usr/src
        - name: dockerplugins
          hostPath:
            path: /run/docker/plugins
        - name: hostproc
          hostPath:
            path: /proc
        {{- end }}
{{- end }}