---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: portworx-operator
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["*"]
  {{- if semverCompare "<1.25" (.Capabilities.KubeVersion.Version) }}
  - apiGroups: ["policy"]
    resources: ["podsecuritypolicies"]
    resourceNames: ["px-operator"]
    verbs: ["use"]
  {{- end }}