{{- if (.Values.clusterToken.create) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.clusterToken.secretName }}
  namespace:  portworx
  labels:
    name: {{ .Values.clusterToken.secretName }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{.Release.Service | quote }}
    app.kubernetes.io/instance: {{.Release.Name | quote }}
    chart: "{{.Chart.Name}}-{{.Chart.Version}}"
type: "Opaque"
data:
  cluster-wide-secret-key: {{ template "portworx-cluster-key"  }}
{{- end }}
