apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgres-pg-01
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    app.kubernetes.io/name: postgres
    app.kubernetes.io/instance: pg-01
spec:
  project: default
  source:
    repoURL: https://github.com/portworx/helm.git
    targetRevision: argo-sap
    path: chart
    helm:
      releaseName: postgres-pg-01
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: pg-01
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - ApplyOutOfSyncOnly=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
    retry:
      limit: 5
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 5m
  revisionHistoryLimit: 10
