apiVersion: batch/v1
kind: Job
metadata:
  name: px-hook-retain-daemonset-resources
  labels:
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
  annotations:
    helm.sh/hook: pre-upgrade
    helm.sh/hook-weight: "10"
    helm.sh/hook-delete-policy: before-hook-creation
spec:
  template:
    spec:
      {{- if .Values.global.image.pullSecret }}
      imagePullSecrets:
        - name: {{ .Values.global.image.pullSecret }}
      {{- end }}
      serviceAccountName: {{ template "px.hookServiceAccount" . }}
      restartPolicy: Never
      containers:
        - name: retain-px-daemonset
          image: "{{ .Values.kubectl.image.repository }}:{{ default .Capabilities.KubeVersion.Version .Values.kubectl.image.tag }}"
          command: ['/bin/sh',
                    '-c',
                    'kubectl -n {{ .Release.Namespace }} annotate DaemonSet portworx-api helm.sh/resource-policy=keep --overwrite;
                     kubectl -n {{ .Release.Namespace }} annotate DaemonSet portworx helm.sh/resource-policy=keep --overwrite || true;
                     kubectl -n {{ .Release.Namespace }} annotate Service stork-service helm.sh/resource-policy=keep --overwrite || true;
                     kubectl -n {{ .Release.Namespace }} annotate Service prometheus helm.sh/resource-policy=keep --overwrite || true;
                     kubectl -n {{ .Release.Namespace }} annotate Service portworx-service helm.sh/resource-policy=keep --overwrite || true;
                     kubectl -n {{ .Release.Namespace }} annotate Service autopilot helm.sh/resource-policy=keep --overwrite || true;
                     kubectl -n {{ .Release.Namespace }} annotate Service grafana helm.sh/resource-policy=keep --overwrite || true;
                     kubectl -n {{ .Release.Namespace }} annotate Service alertmanager-portworx helm.sh/resource-policy=keep --overwrite || true;
                     kubectl -n {{ .Release.Namespace }} annotate Service px-csi-service helm.sh/resource-policy=keep --overwrite || true;
                     kubectl -n {{ .Release.Namespace }} annotate Service portworx-api helm.sh/resource-policy=keep --overwrite || true;
                     kubectl -n {{ .Release.Namespace }} annotate Deployment stork-scheduler helm.sh/resource-policy=keep --overwrite || true;
                     kubectl -n {{ .Release.Namespace }} annotate Deployment px-csi-ext helm.sh/resource-policy=keep --overwrite || true;
                     kubectl -n {{ .Release.Namespace }} annotate Deployment autopilot helm.sh/resource-policy=keep --overwrite || true;
                     kubectl -n {{ .Release.Namespace }} annotate Deployment grafana helm.sh/resource-policy=keep --overwrite || true;
                     kubectl -n {{ .Release.Namespace }} annotate Deployment stork helm.sh/resource-policy=keep --overwrite || true;
                     kubectl -n {{ .Release.Namespace }} annotate Deployment prometheus-operator helm.sh/resource-policy=keep --overwrite || true;

                     kubectl -n {{ .Release.Namespace }} annotate RoleBinding px-role-binding helm.sh/resource-policy=keep --overwrite || true;
                     kubectl -n {{ .Release.Namespace }} annotate Role px-role helm.sh/resource-policy=keep --overwrite || true;
                     kubectl annotate ClusterRoleBinding stork-scheduler-role-binding helm.sh/resource-policy=keep --overwrite || true;
                     kubectl annotate ClusterRoleBinding stork-role-binding helm.sh/resource-policy=keep --overwrite || true;
                     kubectl annotate ClusterRoleBinding node-role-binding helm.sh/resource-policy=keep --overwrite || true;
                     kubectl annotate ClusterRoleBinding prometheus helm.sh/resource-policy=keep --overwrite || true;
                     kubectl annotate ClusterRoleBinding px-csi-role-binding helm.sh/resource-policy=keep --overwrite || true;
                     kubectl annotate ClusterRoleBinding autopilot-role-binding helm.sh/resource-policy=keep --overwrite || true;
                     kubectl annotate ClusterRoleBinding prometheus-operator helm.sh/resource-policy=keep --overwrite || true;

                     kubectl annotate ClusterRole stork-scheduler-role helm.sh/resource-policy=keep --overwrite || true;
                     kubectl annotate ClusterRole autopilot-role helm.sh/resource-policy=keep --overwrite || true;
                     kubectl annotate ClusterRole prometheus helm.sh/resource-policy=keep --overwrite || true;
                     kubectl annotate ClusterRole prometheus-operator helm.sh/resource-policy=keep --overwrite || true;
                     kubectl annotate ClusterRole node-get-put-list-role helm.sh/resource-policy=keep --overwrite || true;
                     kubectl annotate ClusterRole px-csi-role helm.sh/resource-policy=keep --overwrite || true;
                     kubectl annotate ClusterRole stork-role helm.sh/resource-policy=keep --overwrite || true;

                     kubectl annotate StorageClass stork-snapshot-sc helm.sh/resource-policy=keep --overwrite || true;
                     kubectl annotate StorageClass portworx-shared-sc helm.sh/resource-policy=keep --overwrite || true;
                     kubectl annotate StorageClass portworx-db2-sc helm.sh/resource-policy=keep --overwrite || true;
                     kubectl annotate StorageClass portworx-null-sc helm.sh/resource-policy=keep --overwrite || true;
                     kubectl annotate StorageClass portworx-db-sc helm.sh/resource-policy=keep --overwrite || true;

                     kubectl -n {{ .Release.Namespace }} annotate ConfigMap grafana-dashboard-config helm.sh/resource-policy=keep --overwrite || true;
                     kubectl -n {{ .Release.Namespace }} annotate ConfigMap autopilot-config helm.sh/resource-policy=keep --overwrite || true;
                     kubectl -n {{ .Release.Namespace }} annotate ConfigMap grafana-dashboards helm.sh/resource-policy=keep --overwrite || true;
                     kubectl -n {{ .Release.Namespace }} annotate ConfigMap grafana-source-config helm.sh/resource-policy=keep --overwrite || true;
                     kubectl -n {{ .Release.Namespace }} annotate ConfigMap stork-config helm.sh/resource-policy=keep --overwrite || true;

                     kubectl -n {{ .Release.Namespace }} annotate ServiceAccount stork-scheduler-account helm.sh/resource-policy=keep --overwrite || true;
                     kubectl -n {{ .Release.Namespace }} annotate ServiceAccount px-account helm.sh/resource-policy=keep --overwrite || true;
                     kubectl -n {{ .Release.Namespace }} annotate ServiceAccount prometheus-operator helm.sh/resource-policy=keep --overwrite || true;
                     kubectl -n {{ .Release.Namespace }} annotate ServiceAccount px-csi-account helm.sh/resource-policy=keep --overwrite || true;
                     kubectl -n {{ .Release.Namespace }} annotate ServiceAccount stork-account helm.sh/resource-policy=keep --overwrite || true;
                     kubectl -n {{ .Release.Namespace }} annotate ServiceAccount prometheus helm.sh/resource-policy=keep --overwrite || true;
                     kubectl -n {{ .Release.Namespace }} annotate ServiceAccount autopilot-account helm.sh/resource-policy=keep --overwrite || true;

                     kubectl -n {{ .Release.Namespace }} annotate Alertmanager portworx helm.sh/resource-policy=keep --overwrite || true;
                     kubectl annotate CSIDriver pxd.portworx.com helm.sh/resource-policy=keep --overwrite || true;
                     kubectl -n {{ .Release.Namespace }} annotate Prometheus prometheus helm.sh/resource-policy=keep --overwrite || true;
                     kubectl -n {{ .Release.Namespace }} annotate PrometheusRule prometheus-portworx-rules-portworx.rules.yaml helm.sh/resource-policy=keep --overwrite || true;
                     kubectl -n {{ .Release.Namespace }} annotate ServiceMonitor portworx-prometheus-sm helm.sh/resource-policy=keep --overwrite || true;
                     ']
