{{- if .Values.cacheAgent.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.cacheAgent.serviceAccount.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "px-observability-ui.cacheAgent.labels" . | nindent 4 }}
automountServiceAccountToken: true
{{- end }}
