{{- if .Values.deployCluster }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: px-hook-delete-storagecluster
  labels:
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
  annotations:
    helm.sh/hook: pre-delete
    helm.sh/hook-weight: "10"
    helm.sh/hook-delete-policy: before-hook-creation
spec:
  backoffLimit: 0
  template:
    spec:
      {{- if .Values.global.image.pullSecret }}
      imagePullSecrets:
        - name: {{ .Values.global.image.pullSecret }}
      {{- end }}
      serviceAccountName: {{ template "px.hookServiceAccount" . }}
      restartPolicy: Never
      containers:
        - name: delete-storagecluster
          image: "{{ .Values.kubectl.image.repository }}:{{ default .Capabilities.KubeVersion.Version .Values.kubectl.image.tag }}"
          command: ['/bin/sh',
                    '-c',
                    'kubectl -n {{ .Release.Namespace }} delete storagecluster {{ .Values.clusterName }} --ignore-not-found']
{{- end }}
