pxlicenseserver:
  internal:
    enabled: true
    lsTypeUAT: false
    lsTypeAirgapped: false
  external:
    enabled: false
  mainNodeIP: ""
  backupNodeIP: ""
  adminUserName: admin
  adminUserPassword: Password@1

securityContext:
  runAsUser: 1000
  fsGroup: 1000
  runAsNonRoot: true

images:
  pullSecrets:
    - docregistry-secret
  pullPolicy: Always

  licenseServerImage:
    registry: docker.io
    repo: portworx
    imageName: px-els
    tag: 1.0.0
  pxLicenseHAConfigContainerImage:
    registry: docker.io
    repo: portworx
    imageName: pxcentral-onprem-els-ha-setup
    tag: 1.1.1