---
kind: ClusterRole
apiVersion: {{ template "rbac.apiVersion" . }}
metadata:
  annotations:
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded
    helm.sh/hook: post-install,pre-upgrade,pre-delete
  name: {{ template "px.hookClusterRole" . }}
rules:
  # for daemonset to operator migration, we need hooks for all resources deployed by daemonset, due to resources are
  # different in different helm charts (GCP, IKS, Rancher and portworx), we use wild card here. After daemonset
  # migration is finished for all customers we shall change this back to limited access.
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["*"]