{{- $pxBackupEnabled := .Values.pxbackup.enabled | default false }}
{{- if eq $pxBackupEnabled true }}
{{- $isOpenshiftCluster := or .Values.isOpenshift (.Capabilities.APIVersions.Has "apps.openshift.io/v1") -}}
{{- $deployDedicatedMonitoringSystem := .Values.pxbackup.deployDedicatedMonitoringSystem }}
{{- $azureProxyEnabled := .Values.proxy.azureProxyEnabled | default false }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pxc-prometheus-operator
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: px-backup
{{- include "px-central.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: pxc-prometheus-operator
    namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: pxc-prometheus-operator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pxc-prometheus-operator
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: px-backup
{{- include "px-central.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - extensions
    resources:
      - thirdpartyresources
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups:
      - apiextensions.k8s.io
    resources:
        - customresourcedefinitions
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups:
      - monitoring.coreos.com
    resources:
        - alertmanagers
        - alertmanagers/status
        - alertmanagers/finalizers
        - prometheuses
        - prometheuses/finalizers
        - prometheuses/status
        - servicemonitors
        - prometheusrules
        - podmonitors
        - thanosrulers
        - alertmanagerconfigs
        - probes
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups:
      - apps
    resources:
      - statefulsets
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: [""]
    resources:
      - configmaps
      - secrets
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: [""]
    resources:
      - pods
    verbs: ["list", "delete"]
  - apiGroups: [""]
    resources:
      - services
      - endpoints
    verbs: ["get", "create", "update"]
  - apiGroups: [""]
    resources:
      - nodes
    verbs: ["list", "watch"]
  - apiGroups: [""]
    resources:
      - namespaces
    verbs: ["list", "watch", "get"]

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: pxc-prometheus-operator
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: px-backup
{{- include "px-central.labels" . | nindent 4 }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    k8s-app: prometheus-operator
    app.kubernetes.io/component: px-backup
{{- include "px-central.labels" . | nindent 4 }}
  name: prometheus-operator
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      k8s-app: prometheus-operator
  replicas: 1
  template:
    metadata:
      labels:
        k8s-app: prometheus-operator
{{- include "px-central.partOfLabel" . | nindent 8 }}
      {{- if and (eq $azureProxyEnabled true) (not (has "prometheus-operator" .Values.proxy.excludeAzureProxyList)) }}
      annotations:
        kubernetes.azure.com/no-http-proxy-vars: "true"
      {{- end }}
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              {{- if .Values.nodeAffinityLabel }}
              - key: {{ .Values.nodeAffinityLabel }}
                operator: Exists
              {{- else }}
              - key: pxbackup/enabled
                operator: NotIn
                values:
                - "false"
              {{- end }}
      containers:
      - args:
          - -namespaces={{ .Release.Namespace }}
          - --kubelet-service={{ .Release.Namespace }}/kubelet
          - --prometheus-config-reloader={{ printf "%s/%s/%s:%s" (default .Values.images.pxBackupPrometheusConfigReloaderImage.registry .Values.images.registry) (default .Values.images.pxBackupPrometheusConfigReloaderImage.repo .Values.images.repo) .Values.images.pxBackupPrometheusConfigReloaderImage.imageName .Values.images.pxBackupPrometheusConfigReloaderImage.tag }}
        image: {{ printf "%s/%s/%s:%s" (default .Values.images.pxBackupPrometheusOperatorImage.registry .Values.images.registry) (default .Values.images.pxBackupPrometheusOperatorImage.repo .Values.images.repo) .Values.images.pxBackupPrometheusOperatorImage.imageName .Values.images.pxBackupPrometheusOperatorImage.tag }}
        name: prometheus-operator
        ports:
          - containerPort: 8080
            name: http
        volumeMounts:
        {{- if .Values.proxy.configSecretName }}
          - mountPath: /etc/ssl/certs/proxy-ca.pem
            subPath: proxy-ca.pem
            name: proxy-ca-volume
            readOnly: true
        {{- end }}
        env:
        {{- include "serviceMesh.env" . | nindent 8 }}
        {{- if .Values.proxy.httpProxy.noProxy }}
        {{- if or (empty .Values.proxy.includeNoProxyList) (has "prometheus-operator" .Values.proxy.includeNoProxyList) }}
        {{ include "proxy.proxyEnv" . | nindent 8 }}
        {{- end }}
        {{- end }}
        {{- if $isOpenshiftCluster }}
        {{- else }}
      securityContext:
{{ toYaml .Values.securityContext | indent 8 }}
      {{- end }}
      serviceAccountName: pxc-prometheus-operator
      volumes:
      {{- if .Values.proxy.configSecretName }}
        - name: proxy-ca-volume
          secret:
            items:
            - key: CA
              path: proxy-ca.pem
            optional: true
            secretName: {{ .Values.proxy.configSecretName }}
      {{- end }}
      {{- if .Values.images.pullSecrets }}
      imagePullSecrets:
          {{- range $sec := .Values.images.pullSecrets }}
          - name: {{ $sec | quote }}
          {{- end }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
      {{- toYaml . | nindent 8 }}
      {{- end }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: px-backup-dashboard-prometheus
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: px-backup
{{- include "px-central.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  - services
  - endpoints
  - pods
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
- nonResourceURLs:
  - /metrics
  - /federate
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: px-backup-dashboard-prometheus
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: px-backup
{{- include "px-central.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: px-backup-dashboard-prometheus
subjects:
- kind: ServiceAccount
  name: px-backup-dashboard-prometheus
  namespace: {{ .Release.Namespace }}
---
apiVersion: v1
kind: Service
metadata:
  name: px-backup-dashboard-prometheus
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: px-backup
{{- include "px-central.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: http-web
      port: 9090
      protocol: TCP
      targetPort: 9090
  selector:
    prometheus: px-backup-dashboard-prometheus
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: px-backup-dashboard-prometheus
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: px-backup
{{- include "px-central.labels" . | nindent 4 }}
{{- end -}}
