apiVersion: batch/v1
kind: Job
metadata:
  namespace: kube-system
  name: px-postdelete-unlabelnode
  labels:
    heritage: {{.Release.Service | quote }}
    release: {{.Release.Name | quote }}
    chart: "{{.Chart.Name}}-{{.Chart.Version}}"
  annotations:
    "helm.sh/hook": post-delete
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  backoffLimit: 1
  template:
    spec:
      serviceAccountName: tiller
      restartPolicy: OnFailure
      volumes:
      - name: kubectl
        hostPath:
          path: /usr/bin/kubectl
      containers:
      - name: post-delete-job
        image: "lachlanevenson/k8s-kubectl:{{ .Capabilities.KubeVersion.GitVersion }}"
        volumeMounts:
        - name: kubectl
          mountPath: /kubectl
        command:
        - sh
        - -c
        - "kubectl label nodes --all px/enabled-"