apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  namespace: {{ .Release.Namespace }}
  name: px-backup
  labels:
    app: px-backup
    prometheus: px-backup
    app.kubernetes.io/managed-by: {{.Release.Service }}
spec:
  jobLabel: app
  selector:
    matchLabels:
      app: px-backup
  namespaceSelector:
    any: true
  endpoints:
  - port: rest-api
