name: portworx-daemonSet
version: 2.13.5
description: A Helm chart for installing Portworx on Kubernetes.
kubeVersion: ">=1.10.0"
appVersion: "2.13.5"
apiVersion: v1
keywords:
  - Storage
  - ICP
  - IKS
  - persistent disk
  - pvc
  - cloud native storage
  - persistent storage
  - portworx
  - amd64
  - Commercial
home: https://portworx.com/
sources:
  - https://github.com/portworx/helm
icon: https://raw.githubusercontent.com/portworx/helm/master/doc/media/k8s-porx.png